### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by sujyQ** [scut-mingqinchen/self2self#12]
Hi.

I'm wondering if you have codes of pytorch version!

Thx.

**Comment by quockaleidoscope** [comment]
Hi @sujyQ , I have a problem running the demo file. Can you tell me the version of keras you used? And do you use tensor-gpu 1.14.0 as specified in the requirements?

**Comment by sujyQ** [comment]
tensorflow-gpu 1.14.0 and keras 2.3.1
would this be a problem?

**Comment by sujyQ** [comment]
Hi @quockaleidoscope , I reinstalled tensorflow-gpu=1.14.0 and problem solved!
